apiVersion: v1
kind: Pod
metadata: 
  name: pod
  labels:
    app: web
spec:
  restartPolicy: Always
  containers:
    - image: nginx:1.28
      name: web
      ports:
        containerPort: 80
      commands:
        - /bin/bash
        - -c
        - ehco $(date) > /var/log/log.txt;
      volumeMounts:
      - mountPath: /var/log
        name: log
