apiVersion: v1
kind: Pod
metadata: 
  name: pod
  labels:
    app: web
spec:
  restartPolicy: Always
  containers:
  - image: nginx:1.28
    name: web
    ports:
      containerPort: 80
  command:
    - /bin/bash
    - -c
    - sleep 600;
