apiVersion: v1
kind: Pod
metadata: 
  name: pod_of_dead
  labels:
    app: web
spec:
  restartPolicy: Always
  containers:
    - image: nginx:1.28
      name: web
      ports:
        containerPort: 80
      commands:
        - /bin/bash
        - -c
        - ehco $(date) > /var/log/log.txt;
      volumeMounts:
      - mountPath: /var/log
        name: log
    - name: db
      image: mariadb
      commands:
        - /bin/basj
        - -c
        - tail -f log.txt
      volumeMounts:
      - mountPath: /var/log
        name: log
  volumes:
  - name: log
    persistentVolumeClaim:
      claimName: log-pvc
