apiVersion: v1
kind: Pod
metadata: 
  name: pod
  labels:
    app: web
spec:
  restartPolicy: Always
  containers:
    - image: nginx:1.28
      name: web
      ports:
        containerPort: 80
      commands:
        - /bin/bash
        - -c
        - ehco $(date) > log.txt;
    - name: db
      image: mariadb
      commands:
        - /bin/basj
        - -c
        - tail -f log.txt
